/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercises01;

import org.junit.Test;
import org.junit.BeforeClass;
import static org.junit.Assert.*;


public class AppTest {
    private static TestLongCounterExperiments testLongCounterExperiments;

    @BeforeClass
    public static void setUp() {
        testLongCounterExperiments = new TestLongCounterExperiments();
    }
    
    @Test public void appHasAGreeting() {
        assertNotNull("app should have a greeting", null);
    }

    @Test public void test1() {
        testLongCounterExperiments.counts = 100;

        assertEquals(20_000_000, testLongCounterExperiments.lc.get());
    }
}
